// Auto-generated by Deploy.s.sol
type ContractAddress = `0x${string}`;

export const PREDICTION_MARKET_ADDRESS = '0xCFDC9B7F4a4c360CF5B3a31Bb33eB46aD8A3dA43' as ContractAddress;
export const EVENT_MARKET_ADDRESS = '0xF625b6c2e77D996D0E793544b8bD9c35Bd9A7663' as ContractAddress;
export const ADMIN_EVENT_ORACLE_ADDRESS = '0xB564f8705840D3cdcFcA61989e0F3752A005eD42' as ContractAddress;
export const USDC_ADDRESS = '0x3600000000000000000000000000000000000000' as ContractAddress;
export const PYTH_ADDRESS = '0x2880aB155794e7179c9eE2e38200202908C17B43' as ContractAddress;
