import {
  WORLDCUP_TEAMS,
  type WorldCupTeam,
} from './worldcup-seed';

export const FLAG_ICON_CODE_BY_TEAM = Object.fromEntries(
  WORLDCUP_TEAMS.map((team) => [team.id, team.flagCode]),
) as Record<WorldCupTeam['id'], string>;

export const FLAG_ICON_BUNDLE_ALLOWLIST = [
  'mx',
  'za',
  'kr',
  'cz',
  'ch',
  'ca',
  'ba',
  'qa',
  'br',
  'ma',
  'gb-sct',
  'ht',
  'us',
  'au',
  'py',
  'tr',
  'de',
  'ci',
  'ec',
  'cw',
  'nl',
  'jp',
  'se',
  'tn',
  'be',
  'eg',
  'ir',
  'nz',
  'es',
  'cv',
  'uy',
  'sa',
  'fr',
  'no',
  'sn',
  'iq',
  'ar',
  'at',
  'dz',
  'jo',
  'co',
  'pt',
  'cd',
  'uz',
  'gb-eng',
  'gh',
  'hr',
  'pa',
] as const;

const FLAG_ICON_URL_BY_CODE: Record<(typeof FLAG_ICON_BUNDLE_ALLOWLIST)[number], string> = {
  mx: new URL('../node_modules/flag-icons/flags/4x3/mx.svg', import.meta.url).href,
  za: new URL('../node_modules/flag-icons/flags/4x3/za.svg', import.meta.url).href,
  kr: new URL('../node_modules/flag-icons/flags/4x3/kr.svg', import.meta.url).href,
  cz: new URL('../node_modules/flag-icons/flags/4x3/cz.svg', import.meta.url).href,
  ch: new URL('../node_modules/flag-icons/flags/4x3/ch.svg', import.meta.url).href,
  ca: new URL('../node_modules/flag-icons/flags/4x3/ca.svg', import.meta.url).href,
  ba: new URL('../node_modules/flag-icons/flags/4x3/ba.svg', import.meta.url).href,
  qa: new URL('../node_modules/flag-icons/flags/4x3/qa.svg', import.meta.url).href,
  br: new URL('../node_modules/flag-icons/flags/4x3/br.svg', import.meta.url).href,
  ma: new URL('../node_modules/flag-icons/flags/4x3/ma.svg', import.meta.url).href,
  'gb-sct': new URL('../node_modules/flag-icons/flags/4x3/gb-sct.svg', import.meta.url).href,
  ht: new URL('../node_modules/flag-icons/flags/4x3/ht.svg', import.meta.url).href,
  us: new URL('../node_modules/flag-icons/flags/4x3/us.svg', import.meta.url).href,
  au: new URL('../node_modules/flag-icons/flags/4x3/au.svg', import.meta.url).href,
  py: new URL('../node_modules/flag-icons/flags/4x3/py.svg', import.meta.url).href,
  tr: new URL('../node_modules/flag-icons/flags/4x3/tr.svg', import.meta.url).href,
  de: new URL('../node_modules/flag-icons/flags/4x3/de.svg', import.meta.url).href,
  ci: new URL('../node_modules/flag-icons/flags/4x3/ci.svg', import.meta.url).href,
  ec: new URL('../node_modules/flag-icons/flags/4x3/ec.svg', import.meta.url).href,
  cw: new URL('../node_modules/flag-icons/flags/4x3/cw.svg', import.meta.url).href,
  nl: new URL('../node_modules/flag-icons/flags/4x3/nl.svg', import.meta.url).href,
  jp: new URL('../node_modules/flag-icons/flags/4x3/jp.svg', import.meta.url).href,
  se: new URL('../node_modules/flag-icons/flags/4x3/se.svg', import.meta.url).href,
  tn: new URL('../node_modules/flag-icons/flags/4x3/tn.svg', import.meta.url).href,
  be: new URL('../node_modules/flag-icons/flags/4x3/be.svg', import.meta.url).href,
  eg: new URL('../node_modules/flag-icons/flags/4x3/eg.svg', import.meta.url).href,
  ir: new URL('../node_modules/flag-icons/flags/4x3/ir.svg', import.meta.url).href,
  nz: new URL('../node_modules/flag-icons/flags/4x3/nz.svg', import.meta.url).href,
  es: new URL('../node_modules/flag-icons/flags/4x3/es.svg', import.meta.url).href,
  cv: new URL('../node_modules/flag-icons/flags/4x3/cv.svg', import.meta.url).href,
  uy: new URL('../node_modules/flag-icons/flags/4x3/uy.svg', import.meta.url).href,
  sa: new URL('../node_modules/flag-icons/flags/4x3/sa.svg', import.meta.url).href,
  fr: new URL('../node_modules/flag-icons/flags/4x3/fr.svg', import.meta.url).href,
  no: new URL('../node_modules/flag-icons/flags/4x3/no.svg', import.meta.url).href,
  sn: new URL('../node_modules/flag-icons/flags/4x3/sn.svg', import.meta.url).href,
  iq: new URL('../node_modules/flag-icons/flags/4x3/iq.svg', import.meta.url).href,
  ar: new URL('../node_modules/flag-icons/flags/4x3/ar.svg', import.meta.url).href,
  at: new URL('../node_modules/flag-icons/flags/4x3/at.svg', import.meta.url).href,
  dz: new URL('../node_modules/flag-icons/flags/4x3/dz.svg', import.meta.url).href,
  jo: new URL('../node_modules/flag-icons/flags/4x3/jo.svg', import.meta.url).href,
  co: new URL('../node_modules/flag-icons/flags/4x3/co.svg', import.meta.url).href,
  pt: new URL('../node_modules/flag-icons/flags/4x3/pt.svg', import.meta.url).href,
  cd: new URL('../node_modules/flag-icons/flags/4x3/cd.svg', import.meta.url).href,
  uz: new URL('../node_modules/flag-icons/flags/4x3/uz.svg', import.meta.url).href,
  'gb-eng': new URL('../node_modules/flag-icons/flags/4x3/gb-eng.svg', import.meta.url).href,
  gh: new URL('../node_modules/flag-icons/flags/4x3/gh.svg', import.meta.url).href,
  hr: new URL('../node_modules/flag-icons/flags/4x3/hr.svg', import.meta.url).href,
  pa: new URL('../node_modules/flag-icons/flags/4x3/pa.svg', import.meta.url).href,
};

export function flagIconCodeForTeam(teamId: WorldCupTeam['id']): string {
  return FLAG_ICON_CODE_BY_TEAM[teamId];
}

export function flagIconUrlForTeam(teamId: WorldCupTeam['id']): string | null {
  const code = flagIconCodeForTeam(teamId) as (typeof FLAG_ICON_BUNDLE_ALLOWLIST)[number];
  return FLAG_ICON_URL_BY_CODE[code] ?? null;
}
