// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Test} from "forge-std/Test.sol";
import {DeployWorldCup} from "../script/DeployWorldCup.s.sol";

contract DeployWorldCupHarness is DeployWorldCup {
    function buildAddressesTs(string memory currentAddresses, address eventMarket, address adminEventOracle)
        external
        pure
        returns (string memory)
    {
        return _buildAddressesTs(currentAddresses, eventMarket, adminEventOracle);
    }
}

contract DeployWorldCupScriptTest is Test {
    DeployWorldCupHarness internal harness;

    function setUp() public {
        harness = new DeployWorldCupHarness();
    }

    function test_BuildAddressesTs_ReplacesExistingWorldCupAddressesAndPreservesFlatConstants() public view {
        address eventMarket = address(0x1234567890AbcdEF1234567890aBcdef12345678);
        address adminEventOracle = address(0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa);
        string memory currentAddresses = string.concat(
            "// Auto-generated by Deploy.s.sol\n",
            "export const PREDICTION_MARKET_ADDRESS = '0x1111111111111111111111111111111111111111' as const;\n",
            "export const EVENT_MARKET_ADDRESS = '0x2222222222222222222222222222222222222222' as const;\n",
            "export const ADMIN_EVENT_ORACLE_ADDRESS = '0x3333333333333333333333333333333333333333' as const;\n",
            "export const USDC_ADDRESS = '0x4444444444444444444444444444444444444444' as const;\n",
            "export const PYTH_ADDRESS = '0x5555555555555555555555555555555555555555' as const;\n"
        );

        string memory actual = harness.buildAddressesTs(currentAddresses, eventMarket, adminEventOracle);

        assertTrue(
            _contains(
                actual,
                "export const PREDICTION_MARKET_ADDRESS = '0x1111111111111111111111111111111111111111' as const;"
            )
        );
        assertTrue(
            _contains(actual, "export const USDC_ADDRESS = '0x4444444444444444444444444444444444444444' as const;")
        );
        assertTrue(
            _contains(actual, "export const PYTH_ADDRESS = '0x5555555555555555555555555555555555555555' as const;")
        );
        assertTrue(_contains(actual, _eventMarketLine(eventMarket)));
        assertTrue(_contains(actual, _adminEventOracleLine(adminEventOracle)));
        assertFalse(_contains(actual, "0x2222222222222222222222222222222222222222"));
        assertFalse(_contains(actual, "0x3333333333333333333333333333333333333333"));
    }

    function test_BuildAddressesTs_AppendsWorldCupAddressesWhenMissing() public view {
        address eventMarket = address(0x1234567890AbcdEF1234567890aBcdef12345678);
        address adminEventOracle = address(0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa);
        string memory currentAddresses = string.concat(
            "// Auto-generated by Deploy.s.sol\n",
            "export const PREDICTION_MARKET_ADDRESS = '0x1111111111111111111111111111111111111111' as const;\n",
            "export const USDC_ADDRESS = '0x4444444444444444444444444444444444444444' as const;\n",
            "export const PYTH_ADDRESS = '0x5555555555555555555555555555555555555555' as const;\n"
        );

        string memory actual = harness.buildAddressesTs(currentAddresses, eventMarket, adminEventOracle);

        assertTrue(
            _contains(
                actual,
                "export const PREDICTION_MARKET_ADDRESS = '0x1111111111111111111111111111111111111111' as const;"
            )
        );
        assertTrue(
            _contains(actual, "export const USDC_ADDRESS = '0x4444444444444444444444444444444444444444' as const;")
        );
        assertTrue(
            _contains(actual, "export const PYTH_ADDRESS = '0x5555555555555555555555555555555555555555' as const;")
        );
        assertTrue(_contains(actual, _eventMarketLine(eventMarket)));
        assertTrue(_contains(actual, _adminEventOracleLine(adminEventOracle)));
    }

    function test_BuildAddressesTs_CreatesMinimalFileWhenCurrentContentIsEmpty() public view {
        address eventMarket = address(0x1234567890AbcdEF1234567890aBcdef12345678);
        address adminEventOracle = address(0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa);

        string memory actual = harness.buildAddressesTs("", eventMarket, adminEventOracle);

        assertTrue(_contains(actual, "// Auto-generated by DeployWorldCup.s.sol"));
        assertTrue(_contains(actual, _eventMarketLine(eventMarket)));
        assertTrue(_contains(actual, _adminEventOracleLine(adminEventOracle)));
    }

    function _eventMarketLine(address eventMarket) internal pure returns (string memory) {
        return string.concat("export const EVENT_MARKET_ADDRESS = '", vm.toString(eventMarket), "' as const;");
    }

    function _adminEventOracleLine(address adminEventOracle) internal pure returns (string memory) {
        return
            string.concat("export const ADMIN_EVENT_ORACLE_ADDRESS = '", vm.toString(adminEventOracle), "' as const;");
    }

    function _contains(string memory value, string memory needle) internal pure returns (bool) {
        bytes memory valueBytes = bytes(value);
        bytes memory needleBytes = bytes(needle);

        if (needleBytes.length == 0) {
            return true;
        }
        if (needleBytes.length > valueBytes.length) {
            return false;
        }

        for (uint256 i = 0; i <= valueBytes.length - needleBytes.length; ++i) {
            bool matched = true;
            for (uint256 j = 0; j < needleBytes.length; ++j) {
                if (valueBytes[i + j] != needleBytes[j]) {
                    matched = false;
                    break;
                }
            }
            if (matched) {
                return true;
            }
        }

        return false;
    }
}
