// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Test} from "forge-std/Test.sol";
import {Deploy} from "../script/Deploy.s.sol";

contract DeployHarness is Deploy {
    function buildAddressesTs(address predictionMarket, address usdc, address pyth)
        external
        view
        returns (string memory)
    {
        return _buildAddressesTs(predictionMarket, usdc, pyth);
    }

    function extractPredictionMarketAbi(string memory artifactJson)
        external
        pure
        returns (string memory)
    {
        return _extractAbiJson(artifactJson);
    }

}

contract DeployScriptTest is Test {
    bytes1 internal constant OPEN_BRACKET = 0x5b;
    string internal constant PREDICTION_MARKET_ARTIFACT_PATH =
        "out/PredictionMarket.sol/PredictionMarket.json";

    DeployHarness internal harness;

    function setUp() public {
        harness = new DeployHarness();
    }

    function test_BuildAddressesTs_ExportsThreeAddressesAsConst() external view {
        address predictionMarket = address(0x1234567890AbcdEF1234567890aBcdef12345678);
        address usdc = address(0x1111111111111111111111111111111111111111);
        address pyth = address(0x2222222222222222222222222222222222222222);

        string memory actual = harness.buildAddressesTs(predictionMarket, usdc, pyth);
        string memory expected = string.concat(
            "// Auto-generated by Deploy.s.sol\n",
            "export const PREDICTION_MARKET_ADDRESS = '",
            vm.toString(predictionMarket),
            "' as const;\n",
            "export const USDC_ADDRESS = '",
            vm.toString(usdc),
            "' as const;\n",
            "export const PYTH_ADDRESS = '",
            vm.toString(pyth),
            "' as const;\n"
        );

        assertEq(actual, expected);
    }

    function test_ExtractPredictionMarketAbi_ReturnsRawAbiArray() external view {
        string memory artifactJson = vm.readFile(PREDICTION_MARKET_ARTIFACT_PATH);

        string memory actual = harness.extractPredictionMarketAbi(artifactJson);

        assertGt(bytes(actual).length, 0);
        assertEq(bytes(actual)[0], OPEN_BRACKET);
        assertTrue(_contains(actual, "\"name\":\"bet\""));
        assertFalse(_contains(actual, "\"bytecode\""));
        assertFalse(_contains(actual, "\"metadata\""));
    }

    function _contains(string memory value, string memory needle) internal pure returns (bool) {
        bytes memory valueBytes = bytes(value);
        bytes memory needleBytes = bytes(needle);

        if (needleBytes.length == 0) {
            return true;
        }
        if (needleBytes.length > valueBytes.length) {
            return false;
        }

        for (uint256 i = 0; i <= valueBytes.length - needleBytes.length; ++i) {
            bool matched = true;
            for (uint256 j = 0; j < needleBytes.length; ++j) {
                if (valueBytes[i + j] != needleBytes[j]) {
                    matched = false;
                    break;
                }
            }
            if (matched) {
                return true;
            }
        }

        return false;
    }
}
