// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Script, console2} from "forge-std/Script.sol";
import {AdminEventOracle} from "../src/AdminEventOracle.sol";
import {EventMarket} from "../src/EventMarket.sol";

contract DeployWorldCup is Script {
    bytes1 internal constant NEWLINE = 0x0a;

    string internal constant WEB_LIB_DIR = "../web/lib";
    string internal constant ADDRESSES_TS_PATH = "../web/lib/addresses.ts";
    string internal constant EVENT_MARKET_PREFIX = "export const EVENT_MARKET_ADDRESS = ";
    string internal constant ADMIN_EVENT_ORACLE_PREFIX = "export const ADMIN_EVENT_ORACLE_ADDRESS = ";

    function run() external {
        uint256 ownerPrivateKey = vm.envUint("OWNER_PRIVATE_KEY");
        address usdc = vm.envAddress("USDC_ADDRESS");
        address feeRecipient = vm.envAddress("FEE_RECIPIENT");
        address bonusBank = vm.envAddress("BONUS_BANK_ADDRESS");
        address ownerEoa = vm.addr(ownerPrivateKey);

        vm.startBroadcast(ownerPrivateKey);
        AdminEventOracle adminEventOracle = new AdminEventOracle(usdc, ownerEoa, feeRecipient, bonusBank, 48);
        EventMarket eventMarket = new EventMarket(usdc, ownerEoa, feeRecipient, address(adminEventOracle));
        vm.stopBroadcast();

        console2.log(unicode"AdminEventOracle 已部署:", address(adminEventOracle));
        console2.log(unicode"EventMarket 已部署:", address(eventMarket));

        _syncFrontendAddresses(address(eventMarket), address(adminEventOracle));
    }

    function _syncFrontendAddresses(address eventMarket, address adminEventOracle) internal {
        vm.createDir(WEB_LIB_DIR, true);
        string memory currentAddresses = vm.exists(ADDRESSES_TS_PATH) ? vm.readFile(ADDRESSES_TS_PATH) : "";
        vm.writeFile(ADDRESSES_TS_PATH, _buildAddressesTs(currentAddresses, eventMarket, adminEventOracle));
    }

    function _buildAddressesTs(string memory currentAddresses, address eventMarket, address adminEventOracle)
        internal
        pure
        returns (string memory)
    {
        string memory addresses = bytes(currentAddresses).length == 0
            ? "// Auto-generated by DeployWorldCup.s.sol\n"
            : currentAddresses;

        addresses = _removeExportLine(addresses, EVENT_MARKET_PREFIX);
        addresses = _removeExportLine(addresses, ADMIN_EVENT_ORACLE_PREFIX);
        addresses = _ensureTrailingNewline(addresses);

        return string.concat(
            addresses,
            _exportAddressLine(EVENT_MARKET_PREFIX, eventMarket),
            "\n",
            _exportAddressLine(ADMIN_EVENT_ORACLE_PREFIX, adminEventOracle),
            "\n"
        );
    }

    function _exportAddressLine(string memory prefix, address value) internal pure returns (string memory) {
        return string.concat(prefix, "'", vm.toString(value), "' as const;");
    }

    function _removeExportLine(string memory input, string memory prefix) internal pure returns (string memory) {
        bytes memory inputBytes = bytes(input);
        bytes memory prefixBytes = bytes(prefix);
        string memory output = "";
        uint256 lineStart = 0;

        while (lineStart < inputBytes.length) {
            uint256 lineEnd = lineStart;
            while (lineEnd < inputBytes.length && inputBytes[lineEnd] != NEWLINE) {
                ++lineEnd;
            }

            string memory line = _slice(inputBytes, lineStart, lineEnd);
            if (!_startsWith(bytes(line), prefixBytes) && bytes(line).length > 0) {
                output = string.concat(output, line, "\n");
            }

            lineStart = lineEnd + 1;
        }

        return output;
    }

    function _startsWith(bytes memory value, bytes memory prefix) internal pure returns (bool) {
        if (prefix.length > value.length) {
            return false;
        }

        for (uint256 i = 0; i < prefix.length; ++i) {
            if (value[i] != prefix[i]) {
                return false;
            }
        }

        return true;
    }

    function _ensureTrailingNewline(string memory value) internal pure returns (string memory) {
        bytes memory valueBytes = bytes(value);
        if (valueBytes.length == 0 || valueBytes[valueBytes.length - 1] == NEWLINE) {
            return value;
        }
        return string.concat(value, "\n");
    }

    function _slice(bytes memory data, uint256 start, uint256 end) internal pure returns (string memory) {
        require(start <= end && end <= data.length, "Invalid slice bounds");

        bytes memory out = new bytes(end - start);
        for (uint256 i = 0; i < out.length; ++i) {
            out[i] = data[start + i];
        }
        return string(out);
    }
}
