// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Script, console2} from "forge-std/Script.sol";
import {PredictionMarket} from "../src/PredictionMarket.sol";

contract Deploy is Script {
    bytes1 internal constant OPEN_BRACKET = 0x5b;
    bytes1 internal constant CLOSE_BRACKET = 0x5d;
    bytes1 internal constant DOUBLE_QUOTE = 0x22;
    bytes1 internal constant BACKSLASH = 0x5c;
    bytes1 internal constant SPACE = 0x20;
    bytes1 internal constant NEWLINE = 0x0a;
    bytes1 internal constant CARRIAGE_RETURN = 0x0d;
    bytes1 internal constant TAB = 0x09;

    string internal constant PREDICTION_MARKET_ARTIFACT_PATH =
        "out/PredictionMarket.sol/PredictionMarket.json";
    string internal constant WEB_LIB_DIR = "../web/lib";
    string internal constant WEB_ABIS_DIR = "../web/lib/abis";
    string internal constant ADDRESSES_TS_PATH = "../web/lib/addresses.ts";
    string internal constant PREDICTION_MARKET_ABI_PATH = "../web/lib/abis/PredictionMarket.json";

    function run() external {
        uint256 ownerPrivateKey = vm.envUint("OWNER_PRIVATE_KEY");
        address usdc = vm.envAddress("USDC_ADDRESS");
        address pyth = vm.envAddress("PYTH_ADDRESS");
        address feeRecipient = vm.envAddress("FEE_RECIPIENT");
        address ownerEoa = vm.addr(ownerPrivateKey);

        vm.startBroadcast(ownerPrivateKey);
        PredictionMarket predictionMarket =
            new PredictionMarket(usdc, pyth, ownerEoa, feeRecipient);
        vm.stopBroadcast();

        console2.log("PredictionMarket deployed:", address(predictionMarket));

        _syncFrontendArtifacts(
            address(predictionMarket),
            usdc,
            pyth,
            PREDICTION_MARKET_ARTIFACT_PATH,
            WEB_LIB_DIR,
            ADDRESSES_TS_PATH,
            WEB_ABIS_DIR,
            PREDICTION_MARKET_ABI_PATH
        );
    }

    function _buildAddressesTs(address predictionMarket, address usdc, address pyth)
        internal
        view
        returns (string memory)
    {
        return string.concat(
            "// Auto-generated by Deploy.s.sol\n",
            "export const PREDICTION_MARKET_ADDRESS = '",
            vm.toString(predictionMarket),
            "' as const;\n",
            "export const USDC_ADDRESS = '",
            vm.toString(usdc),
            "' as const;\n",
            "export const PYTH_ADDRESS = '",
            vm.toString(pyth),
            "' as const;\n"
        );
    }

    function _syncFrontendArtifacts(
        address predictionMarket,
        address usdc,
        address pyth,
        string memory artifactPath,
        string memory webLibDirPath,
        string memory addressesPath,
        string memory abisDirPath,
        string memory predictionMarketAbiPath
    ) internal {
        vm.createDir(webLibDirPath, true);
        vm.createDir(abisDirPath, true);

        vm.writeFile(addressesPath, _buildAddressesTs(predictionMarket, usdc, pyth));

        string memory artifactJson = vm.readFile(artifactPath);
        vm.writeFile(predictionMarketAbiPath, _extractAbiJson(artifactJson));
    }

    function _extractAbiJson(string memory artifactJson) internal pure returns (string memory) {
        bytes memory jsonBytes = bytes(artifactJson);
        bytes memory abiMarker = bytes("\"abi\":");
        uint256 abiStart = _indexOf(jsonBytes, abiMarker);

        require(abiStart != type(uint256).max, "PredictionMarket artifact missing abi");

        abiStart += abiMarker.length;
        while (abiStart < jsonBytes.length && _isWhitespace(jsonBytes[abiStart])) {
            ++abiStart;
        }

        require(
            abiStart < jsonBytes.length && jsonBytes[abiStart] == OPEN_BRACKET,
            "PredictionMarket abi is not array"
        );

        uint256 abiEnd = _findMatchingArrayEnd(jsonBytes, abiStart);
        return _slice(jsonBytes, abiStart, abiEnd + 1);
    }

    function _indexOf(bytes memory haystack, bytes memory needle) internal pure returns (uint256) {
        if (needle.length == 0 || needle.length > haystack.length) {
            return type(uint256).max;
        }

        for (uint256 i = 0; i <= haystack.length - needle.length; ++i) {
            bool matched = true;
            for (uint256 j = 0; j < needle.length; ++j) {
                if (haystack[i + j] != needle[j]) {
                    matched = false;
                    break;
                }
            }
            if (matched) {
                return i;
            }
        }

        return type(uint256).max;
    }

    function _findMatchingArrayEnd(bytes memory value, uint256 start) internal pure returns (uint256) {
        uint256 depth = 0;
        bool inString = false;
        bool escaped = false;

        for (uint256 i = start; i < value.length; ++i) {
            bytes1 char = value[i];

            if (inString) {
                if (escaped) {
                    escaped = false;
                    continue;
                }
                if (char == BACKSLASH)
                    escaped = true;
                else if (char == DOUBLE_QUOTE)
                    inString = false;
                continue;
            }

            if (char == DOUBLE_QUOTE) {
                inString = true;
                continue;
            }
            if (char == OPEN_BRACKET) {
                ++depth;
                continue;
            }
            if (char == CLOSE_BRACKET) {
                --depth;
                if (depth == 0) {
                    return i;
                }
            }
        }

        revert("PredictionMarket abi array is not closed");
    }

    function _isWhitespace(bytes1 char) internal pure returns (bool) {
        return char == SPACE || char == NEWLINE || char == CARRIAGE_RETURN || char == TAB;
    }

    function _slice(bytes memory data, uint256 start, uint256 end) internal pure returns (string memory) {
        require(start <= end && end <= data.length, "Invalid slice bounds");

        bytes memory out = new bytes(end - start);
        for (uint256 i = 0; i < out.length; ++i) {
            out[i] = data[start + i];
        }
        return string(out);
    }
}
