import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import Module from 'node:module';
import ts from 'typescript';

const cwd = process.cwd();
const repoRoot = cwd.endsWith('/web') ? resolve(cwd, '..') : cwd;
const webRoot = cwd.endsWith('/web') ? cwd : resolve(repoRoot, 'web');
const nodeRequire = Module.createRequire(import.meta.url);

const resolveTsSpecifier = (specifier, parentDir) => {
  const directPath = specifier.startsWith('@/') ? resolve(webRoot, specifier.slice(2)) : resolve(parentDir, specifier);
  const candidates = [
    directPath,
    `${directPath}.ts`,
    `${directPath}.tsx`,
    resolve(directPath, 'index.ts'),
    resolve(directPath, 'index.tsx'),
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  return null;
};

const loadTsModule = (modulePath, fresh = false) => {
  const moduleCache = fresh ? new Map() : loadTsModule.sharedCache;
  if (moduleCache.has(modulePath)) {
    return moduleCache.get(modulePath);
  }

  if (!existsSync(modulePath)) {
    throw new Error(`缺少文件: ${modulePath}`);
  }

  const source = readFileSync(modulePath, 'utf8');
  const { outputText, diagnostics } = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      jsx: ts.JsxEmit.ReactJSX,
      esModuleInterop: true,
      moduleResolution: ts.ModuleResolutionKind.Node10,
    },
    fileName: modulePath,
    reportDiagnostics: true,
  });

  if (diagnostics?.length) {
    const message = ts.formatDiagnosticsWithColorAndContext(diagnostics, {
      getCurrentDirectory: () => repoRoot,
      getCanonicalFileName: (fileName) => fileName,
      getNewLine: () => '\n',
    });
    throw new Error(`TypeScript 转译失败:\n${message}`);
  }

  const module = { exports: {} };
  moduleCache.set(modulePath, module.exports);

  const localRequire = (specifier) => {
    if (specifier.startsWith('.') || specifier.startsWith('@/')) {
      const resolved = resolveTsSpecifier(specifier, dirname(modulePath));
      if (!resolved) {
        throw new Error(`无法解析本地依赖: ${specifier} from ${modulePath}`);
      }
      return loadTsModule(resolved, fresh);
    }

    return nodeRequire(specifier);
  };

  const wrapper = new Function(
    'exports',
    'require',
    'module',
    '__filename',
    '__dirname',
    outputText,
  );

  wrapper(module.exports, localRequire, module, modulePath, dirname(modulePath));
  return module.exports;
};

loadTsModule.sharedCache = new Map();

const marketKindPath = resolve(webRoot, 'lib/market-kind.ts');
const featureFlagsPath = resolve(webRoot, 'lib/feature-flags.ts');
const addressesPath = resolve(webRoot, 'lib/addresses.ts');
const eventSourcePath = resolve(webRoot, 'lib/event-source.ts');
const eventAbiPath = resolve(webRoot, 'lib/abis/EventMarket.json');
const oracleAbiPath = resolve(webRoot, 'lib/abis/AdminEventOracle.json');

const marketKind = loadTsModule(marketKindPath);
assert.deepEqual(marketKind.MARKET_KINDS, ['price', 'event']);

const priceRows = [
  { id: 1, question: 'BTC', marketKind: 'price' },
  { id: 2, question: 'ETH' },
];
const eventRows = [
  { id: 3, question: 'ARG vs FRA', marketKind: 'event' },
];

assert.deepEqual(
  marketKind.filterByMarketKind([...priceRows, ...eventRows], 'price').map((row) => row.id),
  [1, 2],
  'price 过滤必须兼容缺省 marketKind 的旧市场。',
);
assert.deepEqual(
  marketKind.filterByMarketKind([...priceRows, ...eventRows], 'event').map((row) => row.id),
  [3],
  'event 过滤必须只返回赛事市场。',
);
assert.equal(marketKind.marketKindOf(priceRows[1]), 'price');
assert.equal(marketKind.marketKindOf(eventRows[0]), 'event');

delete process.env.NEXT_PUBLIC_WORLDCUP_ENABLED;
const featureFlagsOff = loadTsModule(featureFlagsPath, true);
assert.equal(featureFlagsOff.WORLDCUP_ENABLED, false);
process.env.NEXT_PUBLIC_WORLDCUP_ENABLED = 'true';
const featureFlagsOn = loadTsModule(featureFlagsPath, true);
assert.equal(featureFlagsOn.WORLDCUP_ENABLED, true);
delete process.env.NEXT_PUBLIC_WORLDCUP_ENABLED;

const addressesSource = readFileSync(addressesPath, 'utf8');
assert(addressesSource.startsWith('// Auto-generated by Deploy.s.sol'));
assert(addressesSource.includes('export const EVENT_MARKET_ADDRESS ='));
assert(addressesSource.includes('export const ADMIN_EVENT_ORACLE_ADDRESS ='));
assert(!addressesSource.includes('chainId'));

const eventAbi = JSON.parse(readFileSync(eventAbiPath, 'utf8'));
const oracleAbi = JSON.parse(readFileSync(oracleAbiPath, 'utf8'));
assert(Array.isArray(eventAbi), 'EventMarket ABI 必须导出数组 JSON。');
assert(Array.isArray(oracleAbi), 'AdminEventOracle ABI 必须导出数组 JSON。');
assert(eventAbi.some((entry) => entry.name === 'createMarket'));
assert(oracleAbi.some((entry) => entry.name === 'proposeResult'));

delete process.env.SPORTSDB_API_BASE;
delete process.env.NEXT_PUBLIC_SPORTSDB_API_BASE;
const eventSourceDefault = loadTsModule(eventSourcePath, true);
assert.equal(
  eventSourceDefault.SPORTSDB_API_BASE,
  'https://www.thesportsdb.com/api/v1/json/123',
);
process.env.SPORTSDB_API_BASE = 'https://internal.example/api';
const eventSourceInternal = loadTsModule(eventSourcePath, true);
assert.equal(eventSourceInternal.SPORTSDB_API_BASE, 'https://internal.example/api');
process.env.NEXT_PUBLIC_SPORTSDB_API_BASE = 'https://public.example/api';
const eventSourcePublic = loadTsModule(eventSourcePath, true);
assert.equal(eventSourcePublic.SPORTSDB_API_BASE, 'https://public.example/api');
delete process.env.SPORTSDB_API_BASE;
delete process.env.NEXT_PUBLIC_SPORTSDB_API_BASE;

eventSourceDefault.clearLiveScoreCache();
assert.equal(eventSourceDefault.readLiveScoreCache('match-1', 1000), null);
eventSourceDefault.writeLiveScoreCache('match-1', { status: 'success', score: { home: 1, away: 0, label: "67'" }, ts: 1000 });
assert.deepEqual(
  eventSourceDefault.readLiveScoreCache('match-1', 1500),
  { status: 'success', score: { home: 1, away: 0, label: "67'" }, ts: 1000 },
);
assert.equal(eventSourceDefault.readLiveScoreCache('match-1', 61_500), null);
assert.equal(
  eventSourceDefault.buildSportsDbEventUrl('group-a-1'),
  'https://www.thesportsdb.com/api/v1/json/123/lookupevent.php?id=1543883',
);
assert.equal(
  eventSourceDefault.resolveSportsDbEventId('group-a-1'),
  '1543883',
);
assert.equal(
  eventSourceDefault.resolveSportsDbEventId('qf-1'),
  null,
);
assert.equal(
  eventSourceDefault.buildSportsDbEventUrl('qf-1'),
  null,
  '未知 provider id 的场次不能拼出 lookupevent.php?id=qf-1 这样的危险 URL。',
);

console.log('worldcup data layer 检查通过');
